apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:<PASSWORD>@postgres:5432/applications_and_events?schema=public"
  JWT_ACCESS_SECRET: "change-me-in-production-access"
  JWT_REFRESH_SECRET: "change-me-in-production-refresh"
  REDIS_URL: "redis://redis:6379"
